version: '3.7'

services:
  db:
    image: postgres:16-alpine
    ports:
      - 5433:5432
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: on-failure
